config/routes.rb
Rails.application.routes.draw do

	mount Ckeditor::Engine => '/ckeditor'
	ActiveAdmin.routes(self)
	
	root 'home#index'
	
	################

	# get 'connexion' => 'users#new', as: :login
	# post 'connexion' => 'sessions#create'
	# get 'deconnexion' => 'sessions#destroy', as: :logout

	# get 'auth/:provider/callback' => 'sessions#create'
	# get 'auth/failure' => 'sessions#failure'

	resource :users, only: [:new, :create], path: 'utilisateurs'

	################

	match 'contact' => 'home#contact', via: [:get, :post], as: :contact

	get 'faq' => 'home#faq', as: :faq
	get 'cgu' => 'home#cgu', as: :terms
	get 'confidentialité' => 'home#privacy', as: :privacy
	get 'cgv' => 'home#cgv', as: :cgv
	get 'a-propos' => 'home#about', as: :about

	get 'recherche' => 'home#search', as: :search
	get 'suggestion' => 'home#suggest', as: :suggest

	resources :posts, except: [:create, :destroy], path: 'annonces', path_names: { new: 'nouvelle', edit: 'edition' } do
		member do
			post 'upload'
			post 'remove_media'
			match 'contact', via: [:get, :post]

			get 'phones'
			get 'delete'
		end
	end

	get 'sitemap' => 'sitemap#index'
	get 'opensearch' => 'home#opensearch', as: :opensearch

end

app/views/partials/_footer.html.erb
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="push-cl-2 cl-2">
				<h5>Société</h5>
				<ul>
					<li><%= link_to 'Blog', 'http://blog.mobile-d-occaz.fr', title: 'Blog', target: '_blank' %></li>
					<li><% link_to 'A propos', about_path, title: 'A propos' %></li>
					<li><%= link_to 'Contact', contact_path, title: 'Contact' %></li>
					<li><%= link_to 'FAQ', faq_path, title: 'FAQ' %></li>
				</ul>
			</div>
			<div class="cl-2">
				<h5>Légale</h5>
				<ul>
					<li><%= link_to 'CGU', terms_path, title: 'Conditions Générales d\'Utilisation' %></li>
					<!-- <li><% link_to 'CGV', cgv_path, title: 'Conditions Générales de Vente' %></li> -->
					<li><%= link_to 'Confidentialité', privacy_path, title: 'Politique de confidentialité' %></li>
				</ul>
			</div>
			<div class="push-cl-2 cl-3">
				<h5>Réseaux sociaux</h5>
				<ul class="social">
					<li><a target="_blank" href="https://www.facebook.com/mobiledoccaz" class="icon-footer icon-facebook" title="Facebook"></a></li>
					<li><a target="_blank" href="https://twitter.com/mobiledoccaz" class="icon-footer icon-twitter" title="Twitter"></a></li>
					<li><a target="_blank" href="https://plus.google.com/117817770911874034817" class="icon-footer icon-google" title="Google Plus"></a></li>
					<li><a target="_blank" href="https://www.linkedin.com/company/mobile-d%27occaz" class="icon-footer icon-linkedin" title="LinkedIn"></a></li>
				</ul>

				<span id="copyright">&copy; Mobile d'occaz</span>
			</div>
		</div>
	</div>
</div>

app/views/partials/_header.html.erb
<div id="header">
	<div class="container">
		<div class="row">
			<div class="cl-5">
				<div class="logo">
					<%= link_to root_path, title: "Mobile d'occaz" do %>
						<span class="icon-logo"></span>
						<span>Mobile d'occaz</span>
					<% end %>
				</div>
			</div>
			<div class="cl-7">
				<ul>
					<li>
						<%= link_to 'Accueil', root_path, title: 'Accueil' %>
					</li>
					<li>
						<%= link_to 'Aide', faq_path, title: 'Aide' %>
					</li>
					<li>
						<%= link_to 'Vendre mon téléphone', new_post_path, id: 'new_post', title: 'Créer une annonce' %>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/partials/_meta.html.erb
<title><%= print_meta_title %></title>
<meta name="description" content="<%= print_meta_description %>">
<meta name="keywords" content="<%= print_meta_keywords %>">
<link rel="image_src" href="<%= print_meta_image_url %>">

<% if @meta[:cannonical_url] %>
	<link rel="canonical" href="<%= raw @meta[:cannonical_url] %>" />
<% end %>

<% if @meta[:no_index] %>
	<meta name="robots" content="noindex,follow">
<% else %>
	<meta name="robots" content="index,follow">
<% end %>

<link href="https://plus.google.com/117817770911874034817" rel="publisher" />


<meta name="twitter:site" content="@mobiledoccaz" />
<meta name="twitter:creator" content="@mobiledoccaz" />
<meta name="twitter:domain" content="<%= request.host %>" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:url" content="<%= raw(@meta[:cannonical_url] || request.url) %>" />
<meta name="twitter:title" content="<%= print_meta_title %>" />
<meta name="twitter:description" content="<%= print_meta_description %>" />
<meta name="twitter:image" content="<%= print_meta_image_url %>" />

<meta property="og:site_name" content="<%= t('meta.title.global') %>" />
<meta property="og:locale" content="fr_FR" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= raw(@meta[:cannonical_url] || request.url) %>" />
<meta property="og:title" content="<%= print_meta_title %>" />
<meta property="og:description" content="<%= print_meta_description %>" />
<meta property="og:image" content="<%= print_meta_image_url %>" />

app/views/partials/_search.html.erb
<div class="cl-5">
	<div class="input">
		<%= text_field_tag :q, params[:q], class: 'icon-search icon-phone', placeholder: "Ex: iPhone 5" %>
	</div>
</div>
<div class="cl-5">
	<div class="input autocomplete-place-geocode">
		<%= place_field_tag :place, params[:place], class: 'icon-search icon-location' %>
	</div>
</div>
<div class="cl-2">
	<button type="submit" class="button orange-reverse">Rechercher</button>
</div>