config/routes.rb
Rails.application.routes.draw do

	mount Ckeditor::Engine => '/ckeditor'
	ActiveAdmin.routes(self)
	
	root 'home#index'
	
	################

	# get 'connexion' => 'users#new', as: :login
	# post 'connexion' => 'sessions#create'
	# get 'deconnexion' => 'sessions#destroy', as: :logout

	# get 'auth/:provider/callback' => 'sessions#create'
	# get 'auth/failure' => 'sessions#failure'

	resource :users, only: [:new, :create], path: 'utilisateurs'

	################

	match 'contact' => 'home#contact', via: [:get, :post], as: :contact

	get 'faq' => 'home#faq', as: :faq
	get 'cgu' => 'home#cgu', as: :terms
	get 'confidentialité' => 'home#privacy', as: :privacy
	get 'cgv' => 'home#cgv', as: :cgv
	get 'a-propos' => 'home#about', as: :about

	get 'recherche' => 'home#search', as: :search
	get 'suggestion' => 'home#suggest', as: :suggest

	resources :posts, except: [:create, :destroy], path: 'annonces', path_names: { new: 'nouvelle', edit: 'edition' } do
		member do
			post 'upload'
			post 'remove_media'
			match 'contact', via: [:get, :post]

			get 'phones'
			get 'delete'
		end
	end

	get 'sitemap' => 'sitemap#index'
	get 'opensearch' => 'home#opensearch', as: :opensearch

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		@posts = Post::Post.is_public.order_by_date.limit(6).with_images.includes(:brand, :color)

		if params[:place_lat] && params[:place_lng]
			@posts = @posts.order_by_distance_from(params[:place_lat], params[:place_lng])
		end

		@posts = @posts.to_a

		# fresh_when(@posts.first) if flash.empty? && !request.xhr? && @posts.size > 0
	end

	def search
		if !request.xhr? && params[:place] && (params[:place][:lat].blank? || params[:place][:lng].blank?) && !params[:place][:search].blank?
			geocoder = Graticule.service(:google).new(GOOGLE_API_KEY)
			begin
				geo_params = { address: params[:place][:search], components: 'country:fr' }
				response = geocoder.send('make_url', geo_params).open('User-Agent' => Graticule::Geocoder::Base::USER_AGENT).read
				json = JSON.parse(response)
				result = json['results'][0]

				params[:place][:lat] = result['geometry']['location']['lat']
				params[:place][:lng] = result['geometry']['location']['lng']

			    for data in result['address_components']
			    	if data['types'][0] == 'country'
			    		params[:place][:country] = data['long_name']
			    		params[:place][:country_code] = data['short_name']
			        elsif data['types'][0] == 'administrative_area_level_1'
			        	params[:place][:region] = data['long_name']
			        	params[:place][:region_code] = data['short_name']
			        elsif data['types'][0] == 'administrative_area_level_2'
			        	params[:place][:department] = data['long_name']
			        	params[:place][:department_code] = data['short_name']
			        elsif data['types'][0] == 'locality' || data['types'][0] == 'administrative_area3'
			        	params[:place][:city] = data['long_name']
			        elsif data['types'][0] == 'postal_code'
			        	params[:place][:zip_code] = data['long_name']
			        end
			    end		
			rescue
			end
		end

		if params[:radius].blank? || params[:radius].to_i < 1
			params[:radius] = 20
		end

		if params[:amount].blank? || params[:amount].to_i < 1
			params[:amount] = 800
		end

		@posts = Post::Post.is_public.includes(:color, :memory, :state, :medias, :carrier, phone: [:brand, :os])

		@posts = @posts.search_name(params[:q])

		@posts = @posts.where('amount <= ?', params[:amount]) if !params[:amount].blank? && params[:amount].to_i < SEARCH_AMOUNT_MAX

		@posts = @posts.where(brand_id: params[:brand_ids]) if !params[:brand_ids].blank?
		@posts = @posts.where(color_id: params[:color_ids]) if !params[:color_ids].blank?
		@posts = @posts.where(memory_id: params[:memory_ids]) if !params[:memory_ids].blank?
		@posts = @posts.where(state_id: params[:state_ids]) if !params[:state_ids].blank?
		@posts = @posts.where(carrier_id: params[:carrier_ids]) if !params[:carrier_ids].blank?

	
		if !params[:os_ids].blank? || !params[:features].blank?

			# 1st method, seems to be faster

			phones = Phone::Phone.select(:id)

			phones = phones.where(os_id: params[:os_ids]) if !params[:os_ids].blank?

			if !params[:features].blank?
				begin
					for feature in params[:features]
						if Phone::Phone::FEATURES.include?(feature.to_sym)
							phones = phones.where(feature => true)
						end
					end
				rescue
				end
			end

			@posts = @posts.where(phone_id: phones.to_a.map(&:id))

			## 2nd method

			# @posts = @posts.where(phone_phones: { os_id: params[:os_id] }) if !params[:os_id].blank?

			# if !params[:features].blank?
			# 	begin
			# 		for feature in parms[:features]
			# 			if Phone::Phone::FEATURES.include?(feature.to_sym)
			# 				@posts = @posts.where(phone_phones: { feature => true })
			# 			end
			# 		end
			# 	rescue
			# 	end
			# end

		end

		if params[:place] && !params[:place][:lat].blank? && !params[:place][:lng].blank?
			if params[:radius].to_i < SEARCH_RADIUS_MAX
				@posts = @posts.where_distance_is_less_than(params[:place][:lat], params[:place][:lng], params[:radius].to_i)
			else
				@posts = @posts.order_by_distance_from(params[:place][:lat], params[:place][:lng])
			end
		end

		@posts = @posts.order_by_date

		@posts_count = @posts.count
		@posts = @posts.page(params[:page])
	end

	def suggest
		posts = Post::Post.is_public.search_name(params[:q]).limit(10).select('DISTINCT(cached_name)').to_a

		render json: [
			params[:q],
			posts.map(&:cached_name)
		]
	end

	def contact
		if request.post? && params[:message]
			@message = Message.new(messages_params)
			@message.remote_ip = request.remote_ip
			
			if @message.save
				flash[:notice] = I18n.t('flash.message_sent')
				redirect_to root_url
			end
		else
			@message = Message.new
		end
	end

	def cgv
		@page = Page.find_by_str_key!('cgv')
		render_page
	end

	def faq
		@page = Page.find_by_str_key!('faq')
		render_page
	end

	def privacy
		@page = Page.find_by_str_key!('privacy')
		render_page
	end

	def cgu
		@page = Page.find_by_str_key!('cgu')
		render_page
	end

	def about
		@page = Page.find_by_str_key!('about')
		render_page
	end

private

	def messages_params
		params.require(:message).permit!
	end

	def render_page
		set_meta_title(title: @page.name, force: true)
		set_meta_keywords(@page.name)

		render :page # if stale?(@page)
	end

end

app/views/home/_checkbox.html.erb
<div class="search-filter">

	<h4><%= title %></h4>

	<% for obj in  collection %>
		<div class="checkbox">
			<label>
				<%= check_box_tag attr + '[]', obj[:id], params[attr] && params[attr].include?(obj[:id].to_s) %> <%= obj[:name] %>
			</label>
		</div>
	<% end %>

</div>

app/views/home/_home.html.erb
<div class="container">
	<div class="row">
		<div class="cl-12">
			<h2 class="center">
				<%= t '.title' %>
			</h2>
		</div>

		<% for post in @posts %>
			<div class="cl-4">
				<div class="post" itemscope itemtype="http://schema.org/Product">
					<meta itemprop="brand" content="<%= post.brand.name %>" />
					<meta itemprop="manufacturer" content="<%= post.brand.name %>" />
					<meta itemprop="name" content="<%= post.phone_name %>" />
					<meta itemprop="color" content="<%= post.color.name %>" />
					
					<% if post.medias.first %>
						<meta itemprop="image" content="<%= post.medias.first.image.url(:original) %>"
						 />
					<% end %>
	
					<%= link_to post_path(post), title: post.cached_name, itemprop: :url do %>
						<div class="image" style="background-image: url(<%= post.medias.first.image.url(:medium) %>);">
							<div class="filter"></div>
							<div class="amount" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
								<meta itemprop="priceCurrency" content="EUR">
								<span itemprop="price"><%= print_amount post.amount %></span>
							</div>
						</div>
						<div class="center">
							<div class="phone">
								<span><%= post.cached_name %></span>,
								<span><%= post.place_city %></span>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/home/_post.html.erb
<div class="post" itemscope itemtype="http://schema.org/Product">
	<meta itemprop="brand" content="<%= post.brand.name %>" />
	<meta itemprop="manufacturer" content="<%= post.brand.name %>" />

	<% if post.medias.first %>
		<meta itemprop="image" content="<%= post.medias.first.image.url(:original) %>"
		 />
	<% end %>

	<%= link_to post_path(post, return_to: request.url), title: post.cached_name, itemprop: :url do %>

		<div class="left">
			<% if post.medias.first
				post_url = post.medias.first.image.url(:medium)
			else
				post_url = ""
			end %>
			<div class="image" style="background-image: url(<%= post_url %>);"></div>
		</div>

		<div class="details">
			<div class="right amount" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
				<meta itemprop="priceCurrency" content="EUR">
				<h3 itemprop="price"><%= print_amount post.amount %></h3>
			</div>
			<div class="name">
				<h3 itemprop="name"><%= post.phone_name.upcase %></h3>
			</div>
			
			<div class="separator"></div>

			<% if post.color %>
			<div>
				Couleur
				<span itemprop="color"><%= post.color.name %></span>
			</div>
			<% end %>
			<div>
				État
				<span><%= post.state.name %></span>
			</div>
			<div>
				Opérateur
				<span><%= post.carrier.name %></span>
			</div>
			<div>
				Vendu avec son chargeur
				<span><%= print_boolean post.have_charger %></span>
			</div>
			<div>
				Sous garantie
				<span><%= print_boolean post.is_warranty %></span>
			</div>
			<% if post.memory %>
			<div>
				Stockage
				<span><%= post.memory.name %></span>
			</div>
			<% end %>
			<div>
				Envoi par colis
				<span><%= print_boolean post.is_sendable %></span>
			</div>

		</div>

		<div class="footer">
			<span class="right"><%= post.place %></span>
			Mise en ligne le <%= l post.created_at.to_date %>
		</div>

	<% end %>
</div>

app/views/home/_result_text.html.erb
<% if params[:place] && !params[:place][:city].blank? %>
	<%= @posts_count %> Résultats sur <%= params[:place][:city] %>
<% else %>
	<%= @posts_count %> Résultats
<% end %>

app/views/home/_results.html.erb
<%= render partial: 'post', collection: @posts %>
<%= paginate @posts %>

app/views/home/contact.html.erb
<div id="hero" class="min">
	<div id="map-container"></div>
	<div class="filter">
		<div class="container">
			<div class="row">
				<div class="cl-12">
					<h1><%= t '.title' %></h1>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="post-contact" class="new-post-form">
	<div class="container">
		<div class="center intro"><%= t '.content' %></div>

		<%= custom_form_for @message, url: contact_path do |f| %>
			<%= f.text_field :name %>
			<%= f.text_field :email %>
			<%= f.text_field :phone, required: false, info: 'optionnel' %>
			<%= f.text_area :content %>
			<%= f.select :want_copy, options_for_select_boolean(@message.want_copy), { include_blank: false } %>

			<%= f.submit 'Envoyer' %>
		<% end %>
	</div>
</div>

app/views/home/index.html.erb
<%= content_for :javascript do %>
	<%= javascript_include_goole_maps %>
<% end %>

<div id="hero">
	<div id="map-container"></div>
	<div class="filter">
		<div class="container">
			<div class="row">
				<div class="push-cl-3 cl-6">
					<h1>
						<%= raw t '.title' %>
					</h1>
				</div>
			</div>
			<div class="row">
				<div class="cl-12">
					<div id="home-search">
						<div class="row">
							<%= form_tag search_path, method: :get do %>

								<%= render '/partials/search' %>
								
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="home">
	<%= render 'home' %>
</div>

app/views/home/index.js.erb
$('#home').html('<%= j render('home') %>');

app/views/home/opensearch.xml.erb
<?xml version="1.0" encoding="UTF-8" ?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
	<ShortName>Mobile d'occaz</ShortName>
	<Description>Rechercher un téléphone</Description>
	<Image type="image/x-icon"><%= root_url %>favicon.ico</Image>
	<Language>fr</Language>
	<InputEncoding>UTF-8</InputEncoding>
	<Url type="text/html" template="<%= search_url %>?q={searchTerms}&amp;page={startPage?}"/>
	<Url type="application/x-suggestions+json" template="<%= suggest_url %>?q={searchTerms}"/>
</OpenSearchDescription>

app/views/home/page.html.erb
<div id="hero" class="min">
	<div id="map-container"></div>
	<div class="filter">
		<div class="container">
			<div class="row">
				<div class="cl-12">
					<h1><%= @page.name %></h1>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="page">
	<div class="container">
		<div class="row">
			<div class="push-cl-1 cl-10">
				<%= raw @page.content %>
			</div>
		</div>
	</div>
</div>

app/views/home/search.html.erb
<%= content_for :javascript do %>
	<%= javascript_include_tag 'slider' %>
	<%= javascript_include_goole_maps %>
<% end %>

<%= form_tag search_path(ajax: 1), method: :get, remote: true, class: 'jt-auto-submit' do %>

<div id="hero" class="middle">
	<div id="map-container"></div>
	<div class="filter">
		<div class="container">
			<div class="row">
				<div class="cl-12">
					<div id="home-search">
						<div class="row">
							<%= render '/partials/search' %>								
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="push-cl-3 cl-6">
					<h1>
						<%= render 'result_text' %>
					</h1>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="search">
	<div class="container">
		<div class="row">
			<div class="push-cl-1 cl-3">
				<div class="search-filters">

					<div class="search-filter">

						<h4>Distance</h4>

						<div class="slider blue"></div>
						<span class="slider-value"></span>
						<%= hidden_field_tag :radius, params[:radius] %>

					</div>

					<div class="search-filter">

						<h4>Prix</h4>

						<div class="slider orange"></div>
						<span class="slider-value"></span>
						<%= hidden_field_tag :amount, params[:amount] %>

					</div>

					<%= render 'checkbox', collection: Phone::Brand.all, attr: 'brand_ids', title: 'Marques' %>
					<% render 'checkbox', collection: Phone::Os.all, attr: 'os_ids', title: 'OS' %>
					<%= render 'checkbox', collection: Phone::Color.all, attr: 'color_ids', title: 'Couleur' %>
					<%= render 'checkbox', collection: Phone::Memory.all, attr: 'memory_ids', title: 'Capacité' %>
					<%= render 'checkbox', collection: Post::State.all, attr: 'state_ids', title: 'État' %>
					<%= render 'checkbox', collection: Phone::Carrier.all, attr: 'carrier_ids', title: 'Opérateur' %>
					<% render 'checkbox', collection: Phone::Phone::FEATURES.map {|x| {id: x, name: x} }, attr: 'features', title: 'Options' %>
				</div>
			</div>
			<div class="cl-7 search-results">
				<%= render 'results' %>
			</div>
		</div>
	</div>
</div>

<% end %>

app/views/home/search.js.erb
$('.search-results').html('<%= j render('results') %>');
$('h1').html('<%= j render('result_text') %>');
window.history.replaceState({}, '', '<%= j raw(request.original_fullpath.sub('?ajax=1&', '?')) %>');