config/routes.rb
Rails.application.routes.draw do

	mount Ckeditor::Engine => '/ckeditor'
	ActiveAdmin.routes(self)
	
	root 'home#index'
	
	################

	# get 'connexion' => 'users#new', as: :login
	# post 'connexion' => 'sessions#create'
	# get 'deconnexion' => 'sessions#destroy', as: :logout

	# get 'auth/:provider/callback' => 'sessions#create'
	# get 'auth/failure' => 'sessions#failure'

	resource :users, only: [:new, :create], path: 'utilisateurs'

	################

	match 'contact' => 'home#contact', via: [:get, :post], as: :contact

	get 'faq' => 'home#faq', as: :faq
	get 'cgu' => 'home#cgu', as: :terms
	get 'confidentialité' => 'home#privacy', as: :privacy
	get 'cgv' => 'home#cgv', as: :cgv
	get 'a-propos' => 'home#about', as: :about

	get 'recherche' => 'home#search', as: :search
	get 'suggestion' => 'home#suggest', as: :suggest

	resources :posts, except: [:create, :destroy], path: 'annonces', path_names: { new: 'nouvelle', edit: 'edition' } do
		member do
			post 'upload'
			post 'remove_media'
			match 'contact', via: [:get, :post]

			get 'phones'
			get 'delete'
		end
	end

	get 'sitemap' => 'sitemap#index'
	get 'opensearch' => 'home#opensearch', as: :opensearch

end

app/models/post.rb
module Post
  def self.table_name_prefix
    'post_'
  end
end

app/models/post/media.rb
class Post::Media < ActiveRecord::Base

	belongs_to :post

	validates :post_id, presence: true

	has_attached_file :image, styles: { medium: 'x670', thumb: 'x240' }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/post/message.rb
class Post::Message < ActiveRecord::Base

	include Emailable

	belongs_to :post

	validates :post_id, presence: true

	validates :name, :content, presence: true

	after_create :send_mail

	def send_mail
		UserMailer.delay.post_contact(self.id)
		UserMailer.delay.post_contact_copy(self.id) if self.want_copy
	end

end

app/models/post/post.rb
class Post::Post  < ActiveRecord::Base
	
	include Tokenable
	include UID
	include Localizable

	belongs_to :brand, class_name: 'Phone::Brand'
	belongs_to :phone, class_name: 'Phone::Phone'
	belongs_to :memory, class_name: 'Phone::Memory'
	belongs_to :color, class_name: 'Phone::Color'
	belongs_to :carrier, class_name: 'Phone::Carrier'

	belongs_to :state
	belongs_to :user

	has_many :medias, -> { order("post_media.id ASC") }, dependent: :destroy
	has_many :messages, dependent: :destroy

	validates :remote_ip, presence: true
	
	validates :remote_url, uniqueness: { case_sensitive: false }, if: Proc.new { |p| !p.remote_url.blank? }
	validates :remote_url, uniqueness: { case_sensitive: false }, if: Proc.new { |p| !p.remote_url.blank? }

	with_options if: Proc.new { |post| post.is_valided_by_user? } do |post|
		post.validates :brand_id, :color_id, :carrier_id, :state_id, presence: true

		post.validates :amount, presence: true, numericality: { greater_than: 0 }
		post.validates :have_charger, :is_warranty, :is_sendable, :amount_negotiable, inclusion: {:in => [true, false]}

		post.validates :user_email, presence: true, email_format: true
		post.validates :user_name, presence: true

		post.validates :imei, format: { with: /\A(\d){15}$\z/, allow_blank: true }

		post.validate :validates_place

		post.before_validation :set_phone_name
		post.validates :phone_name, presence: true

		post.before_save { self.user_email.downcase! }
		post.before_save :set_cached_name

		post.before_save :create_user
	end

	scope :is_not_deleted, -> { where(is_deleted: false) }

	scope :is_create_by_user, -> { where(remote_url: nil) }
	scope :is_parsed, -> { where("#{self.table_name}.remote_url IS NOT NULL") }
	scope :is_for_admin, -> { is_parsed.where(is_parsed_complete: true).where(is_admin_complete: false) }
	scope :is_for_parse, -> { is_parsed.where(is_parsed_complete: false) }

	# Filtres de 1er niveau

	scope :is_not_valided_by_user, -> { is_not_deleted.where(is_valided_by_user: false) }
	scope :is_public, -> { is_not_deleted.where(is_valided_by_user: true) }

	# Filtres de 2nd niveau

	scope :with_images, -> { joins(:medias).includes(:medias).order('post_media.id ASC') }
	scope :order_by_date, -> { order("#{self.table_name}.created_at DESC") }

	scope :search_name, ->(q) { q.blank? || q.split(' ').size == 0 ? nil : where("LOWER(#{self.table_name}.cached_name) LIKE LOWER(?)", '%' + q.gsub('%', ' ').gsub('_', ' ').split(' ').join('%') + '%') }

	accepts_nested_attributes_for :medias

	def self.create_post_with_user(user, remote_ip)
		post = Post::Post.new(remote_ip: remote_ip)

		if user
			post.user_id = user.id
			post.user_name = user.last_name
			post.user_phone = user.last_phone
			post.user_email = user.email
			
			for attr in [:place_city, :place_zip_code, :place_department, :place_department_code, :place_region, :place_region_code, :place_country, :place_country_code, :place_lat, :place_lng]
				post[attr] = user['last_' + attr.to_s]
			end
		end

		post.save!
		post
	end

	def to_param
		if cached_name
			"#{uid}-#{cached_name.parameterize}"
		else
			"#{uid}"
		end
	end

	def admin_completed!
		self.is_admin_complete = true
		self.save!
	end

	def validates_place
		if self.place_city.blank? || self.place_lat.blank? || self.place_lng.blank?
			if !self.place_search.blank?
				geocoder = Graticule.service(:google).new(GOOGLE_API_KEY)
				begin
					params = { address: self.place_search, components: 'country:fr' }
					response = geocoder.send('make_url', params).open('User-Agent' => Graticule::Geocoder::Base::USER_AGENT).read
					json = JSON.parse(response)
					result = json['results'][0]

					self.place_lat = result['geometry']['location']['lat']
					self.place_lng = result['geometry']['location']['lng']

		            for data in result['address_components']
		            	if data['types'][0] == 'country'
		            		self.place_country = data['long_name']
		            		self.place_country_code = data['short_name']
		                elsif data['types'][0] == 'administrative_area_level_1'
		                	self.place_region = data['long_name']
		                	self.place_region_code = data['short_name']
		                elsif data['types'][0] == 'administrative_area_level_2'
		                	self.place_department = data['long_name']
		                	self.place_department_code = data['short_name']
		                elsif data['types'][0] == 'locality' || data['types'][0] == 'administrative_area3'
		                	self.place_city = data['long_name']
		                elsif data['types'][0] == 'postal_code'
		                	self.place_zip_code = data['long_name']
		                end
		            end		
				rescue
				end
			end
			if self.place_city.blank? || self.place_lat.blank? || self.place_lng.blank?
				errors.add :place_search, I18n.t('errors.messages.blank')
			end
		end
	end

	def set_phone_name
		self.phone_name = self.phone.name if self.phone
	end

	def set_cached_name
		if self.memory
			self.cached_name = "#{self.brand.name} #{self.phone_name} #{self.memory.name}"
		else
			self.cached_name = "#{self.brand.name} #{self.phone_name}"
		end
	end

	def create_user
		if !self.user_id
			user = User.find_or_create_by!(email: self.user_email.to_s.downcase)
			user.update_last_post_infos!(self)

			self.user_id = user.id
		end
	end

	def place
		if place_department_code
			"#{place_city}, #{place_department} (#{place_department_code})"
		else
			"#{place_city}, #{place_department}"
		end
	end

	def meta_title
		"#{self.cached_name} - #{self.place_city}"
	end

	def meta_keywords
		self.cached_name
	end

end

app/models/post/state.rb
class Post::State < ActiveRecord::Base

	has_many :posts, dependent: :destroy

	validates :name, presence: true

	default_scope -> { order("#{self.table_name}.id ASC") }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_public_post, only: [:show]
	before_action :find_post_for_user, only: [:edit, :update, :upload, :remove_media]

	def show
		@medias = @post.medias.to_a

		set_meta_title(name: @post.meta_title)
		set_meta_description(content: @post.content)
		set_meta_cannonical_url(post_url(@post))
		set_meta_keywords(@post.meta_keywords)
		set_meta_image_url(@medias.first.image.url) if @medias.size > 0

		# fresh_when(@post) if flash.empty?
	end
		
	def new
		post = Post::Post.create_post_with_user(current_user, request.remote_ip)
		redirect_to edit_post_url(post)
	end

	def edit		
		@post.carrier_id ||= Phone::Carrier.first.id
		@post.state_id ||= Post::State.find(3).id
		@post.have_charger = true if @post.have_charger.nil?

		@post.medias.build while @post.medias.size < 3

		set_meta_dont_index
	end
	
	def update
		if !params[:is_admin].blank?
			@post.update(posts_params)
			redirect_to root_url
			return
		end

		@post.is_valided_by_user = true
		@post.remote_ip = request.remote_ip

		if @post.update(posts_params)
			# set_current_user(@post.user) if !current_user
			flash[:notice] = I18n.t('flash.post_created')
			redirect_to post_url(@post)

			UserMailer.delay.post_valided_by_user(@post.id)
		else
			@post.medias.new while @post.medias.size < 3
			render :edit
		end
	end

	def upload
		if @post.medias.count >= 3
	 		render nothing: true
	 		return
		end

		media = @post.medias.create(image: params[:file])
		render json: { id: media.id, url: media.image.url(:thumb) }
	end

	def remove_media
		@post.medias.destroy(params[:media_id])

		render nothing: true
	end

	def contact
		@post = Post::Post.is_public.find_by_uid!(params[:id])
		
		if request.post? && params[:post_message]
			@post_message = @post.messages.new(post_messages_params)
			@post_message.remote_ip = request.remote_ip
			if @post_message.save
				flash[:notice] = I18n.t('flash.message_sent')
				redirect_to post_url(@post)
			end
		else
			@post_message = @post.messages.new
		end

		set_meta_dont_index

		set_meta_title(name: @post.meta_title)
		set_meta_description(content: @post.content)
		set_meta_cannonical_url(post_url(@post))
		set_meta_keywords(@post.meta_keywords)
	end

	def delete
		post = Post::Post.is_public.find_by_token! params[:token]
		post.destroy

		flash[:notice] = I18n.t('flash.post_removed')
		redirect_to root_url
	end

	# AJAX

	def phones
		brand = Phone::Brand.find(params[:id])
		render json: brand.phones.select(:id, :name).order(:name).to_a.map {|x| [x.id, x.name] }
	end

private

	def find_public_post
		@post = Post::Post.is_public.find_by_uid(params[:id])
		if !@post
			raise ActionController::RoutingError.new I18n.t('flash.post_expired')
		end
	end

	def find_post_for_user
		if params[:is_admin]
			@post = Post::Post.find_by_uid!(params[:id])
		else
			@post = Post::Post.is_not_valided_by_user.find_by_uid!(params[:id])
		end
	end

	def posts_params
		params.require(:post_post).permit!
	end

	def post_messages_params
		params.require(:post_message).permit!
	end

	def default_url_options(options = {})
		options[:is_admin] = params[:is_admin]
		options
	end

end

app/views/posts/_menu.html.erb
<div id="post_menu">
	<div class="container">
		<div class="row">
			<div class="cl-12">
				<ul>
					<li class="jt-panel-label">
						<a href="#" title="<%= t '.menu_1' %>">1. <%= t '.menu_1' %></a>
					</li>
					<li class="jt-panel-label">
						<a href="#" title="<%= t '.menu_1' %>">2. <%= t '.menu_2' %></a>
					</li>
					<li class="jt-panel-label">
						<a href="#" title="<%= t '.menu_1' %>">3. <%= t '.menu_3' %></a>
					</li>
					<li class="jt-panel-label">
						<a href="#" title="<%= t '.menu_1' %>">4. <%= t '.menu_4' %></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/posts/contact.html.erb
<div id="hero" class="min">
	<div id="map-container"></div>
	<div class="filter">
		<div class="container">
			<div class="row">
				<div class="cl-12">
					<%= link_to "Retour à l'annonce", post_path(@post, return_to: params[:return_to]) %>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="post-contact" class="new-post-form">
	<div class="container">
		<div class="center intro">
			<%= t '.content', name: @post.user_name, product: @post.cached_name %>
		</div>

		<%= custom_form_for @post_message, url: contact_post_path(@post) do |f| %>
			<%= f.text_field :name %>
			<%= f.text_field :email %>
			<%= f.text_field :phone, required: false, info: 'optionnel' %>
			<%= f.text_area :content %>
			<%= f.select :want_copy, options_for_select_boolean(@post_message.want_copy), { include_blank: false } %>

			<%= f.submit 'Envoyer' %>
		<% end %>
	</div>
</div>

app/views/posts/edit.html.erb
<%= content_for :javascript do %>
	<%= javascript_include_goole_maps %>
<% end %>

<div id="hero" class="min">
	<div id="map-container"></div>
	<div class="filter">
		<div class="container">
			<div class="row">
				<div class="cl-12">
					<h1><%= t '.title' %></h1>
				</div>
			</div>
		</div>
	</div>
</div>

<%= render 'menu' %>

<div class="container jt-panel-conatiner new-post-form">
	<%= custom_form_for @post, url: post_path(@post) do |f| %>
		
		<div class="jt-panel">
			<%= f.select :brand_id, options_from_collection_for_select(Phone::Brand.all, :id, :name, @post.brand_id), { include_blank: true } %>
	
			<%= f.hidden_field :phone_id %>			
			<%= f.text_field :phone_name %>

			<%= f.select :memory_id, options_from_collection_for_select(Phone::Memory.all, :id, :name, @post.memory_id), { include_blank: "Je ne sais pas" }, required: false %>

			<%= f.select :color_id, options_from_collection_for_select(Phone::Color.all, :id, :name, @post.color_id), { include_blank: true } %>
			<%= f.select :carrier_id, options_from_collection_for_select(Phone::Carrier.all, :id, :name, @post.carrier_id), { include_blank: true } %>

			<%= f.number_field :imei, required: false, info: 'optionnel', placeholder: "*#06# sur votre téléphone pour obtenir un numéro à 15 chiffres", class: 'jt-validation-imei', max: 999999999999999, autocomplete: :off %>

		</div>

		<div class="jt-panel">
			<%= f.select :state_id, options_from_collection_for_select(Post::State.all, :id, :name, @post.state_id) %>
			<%= f.select :have_charger, options_for_select_boolean(@post.have_charger), { include_blank: true } %>
			<%= f.select :is_warranty, options_for_select_boolean(@post.is_warranty), { include_blank: true } %>
		</div>

		<div class="jt-panel">
			<%= f.number_field :amount, info: 'euro', max: 9999 %>
			<%= f.select :amount_negotiable, options_for_select_boolean(@post.amount_negotiable), { include_blank: false } %>
			<%= f.text_area :content, required: false, info: 'optionnel' %>

			<%= f.fields_for :medias do |g| %>
				<% if g.object && g.object.id %>

					<div class="input-file jt-upload-remove jt-media-id-<%= g.object.id %>" style="background-image: url(<%= g.object.image.url(:thumb) %>)">
						<input type="file" accept="image/bmp,image/gif,image/png,image/jpeg,image/x-ms-bmp"/>
						<a href="#" class="icon-remove">Supprimer</a>
					</div>

				<% else %>

					<div class="input-file jt-upload-ready">
						<input type="file" accept="image/bmp,image/gif,image/png,image/jpeg,image/x-ms-bmp"/>
						<a href="#">Ajouter une photo</a>
					</div>

				<% end %>
			<% end %>
		</div>

		<div class="jt-panel">
			<%= f.text_field :user_name, info: 'affiché sur l\'annonce' %>
			<%= f.email_field :user_email, info: 'non visible sur l\'annonce' %>
			<%= f.text_field :user_phone, required: false, info: 'optionnel' %>

			<div class="autocomplete-place-cities">
				<%= f.place_field :place, placeholder: "Indiquez le nom de votre ville" %>

				<div class="row hidden">
					<div class="push-cl-3 cl-6">
						<div id="input-map-container"></div>
					</div>
				</div>
			</div>
			
			<%= f.select :is_sendable, options_for_select_boolean(@post.is_sendable), { include_blank: false } %>

			<%= f.submit %>
		</div>

		<div class="row">
			<div class="cl-10"></div>
			<div class="cl-2">
				<a class="button orange jt-panel-next right" href="#">Suivant</a>
			</div>
		</div>

	<% end %>
</div>

app/views/posts/show.html.erb
<div id="hero" class="min">
	<div id="map-container"></div>
	<div class="filter">
		<div class="container">
			<div class="row">
				<div class="cl-12">
					<% if params[:return_to] %>
						<%= link_to 'Retour à la recherche', params[:return_to], title: 'Retour à la recherche' %>
					<% else %>
						<%= link_to 'Retour à l\'accueil', root_path, title: 'Retour à l\'accueil' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="post" itemscope itemtype="http://schema.org/Product">
	
	<% if @medias.first %>
		<meta itemprop="image" content="<%= @medias.first.image.url(:original) %>"
		 />
	<% end %>

	<div class="container">
		<div class="row">
			
			<% if @medias.size > 0 %>

				<div class="cl-5">
					<div class="images">
						<div class="big">
							<div></div>
						</div>
					</div>
				</div>
				<div class="push-cl-1 cl-4">

			<% else %>

				<div class="cl-6">
					<div class="description">
						<% if !@post.content.blank? %>
							<h4>Description:</h4>
							<%= simple_format @post.content, itemprop: "description" %>
						<% end %>
					</div>
				</div>
				<div class="cl-4">

			<% end %>

				<div class="details">
					<h1 class="center">
						<meta itemprop="manufacturer" content="<%= @post.brand.name %>" />
						<span itemprop="brand"><%= @post.brand.name %></span> - 
						<span itemprop="name"><%= @post.phone_name %></span>
					</h1>

					<div class="space"></div>

					<% if @post.color %>
					<div>
						Couleur
						<span itemprop="color"><%= @post.color.name %></span>
					</div>
					<% else %>
						<div>&nbsp;</div>
					<% end %>
					<div>
						État
						<span><%= @post.state.name %></span>
					</div>
					<div>
						Opérateur
						<span><%= @post.carrier.name %></span>
					</div>
					<div>
						Vendu avec son chargeur
						<span><%= print_boolean @post.have_charger %></span>
					</div>
					<div>
						Sous garantie
						<span><%= print_boolean @post.is_warranty %></span>
					</div>
					<div>
						Envoi par colis
						<span><%= print_boolean @post.is_sendable %></span>
					</div>
					<% if @post.memory %>
						<div>
							Stockage
							<span><%= @post.memory.name %></span>
						</div>
					<% else %>
						<div>&nbsp;</div>
					<% end %>
					
					<div class="separator"></div>

					<div class="amount" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
						<meta itemprop="priceCurrency" content="EUR">
						<span itemprop="price" class="price"><%= print_amount @post.amount %></span>

						<% if @post.amount_negotiable %>
							<br>
							<span class="negotiable">(négociable)</span>
						<% end %>
					</div>
				</div>
			</div>
			<div class="cl-2">
				<div class="contact">
					<%= link_to 'Contact', contact_post_path(@post, return_to: params[:return_to]), class: 'button orange-reverse', title: 'Contact' %>

					<div class="space"></div>

					<span class="icon-post icon-name"><%= @post.user_name %></span>
					<span class="icon-post icon-location"><%= @post.place %></span>
					
					<% if !@post.user_phone.blank? %>
						<span class="icon-post icon-phone"><%= @post.user_phone %></span>
					<% end %>

					<span>&nbsp;</span>
					<span class="icon-post icon-date">Mise en ligne le <%= l @post.created_at.to_date %></span>
				</div>
			</div>
		</div>

		<% if @medias.size > 0 %>

			<div class="row">
				<div class="cl-6">
					<div class="images">
						<div class="thumb">
							<% for media in @post.medias.to_a %>
								<%= link_to media.image.url(:medium), style: "background-image: url(#{media.image.url(:thumb)})", target: '_blank', title: 'Afficher l\'image' do %>
									<div class="filter"></div>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
				<div class="cl-6">
					<div class="description">
						<% if !@post.content.blank? %>
							<h4>Description:</h4>
							<%= simple_format @post.content, itemprop: "description" %>
						<% end %>
					</div>
				</div>
			</div>

		<% end %>

	</div>
</div>