config/routes.rb
Rails.application.routes.draw do

	mount Ckeditor::Engine => '/ckeditor'
	ActiveAdmin.routes(self)
	
	root 'home#index'
	
	################

	# get 'connexion' => 'users#new', as: :login
	# post 'connexion' => 'sessions#create'
	# get 'deconnexion' => 'sessions#destroy', as: :logout

	# get 'auth/:provider/callback' => 'sessions#create'
	# get 'auth/failure' => 'sessions#failure'

	resource :users, only: [:new, :create], path: 'utilisateurs'

	################

	match 'contact' => 'home#contact', via: [:get, :post], as: :contact

	get 'faq' => 'home#faq', as: :faq
	get 'cgu' => 'home#cgu', as: :terms
	get 'confidentialité' => 'home#privacy', as: :privacy
	get 'cgv' => 'home#cgv', as: :cgv
	get 'a-propos' => 'home#about', as: :about

	get 'recherche' => 'home#search', as: :search
	get 'suggestion' => 'home#suggest', as: :suggest

	resources :posts, except: [:create, :destroy], path: 'annonces', path_names: { new: 'nouvelle', edit: 'edition' } do
		member do
			post 'upload'
			post 'remove_media'
			match 'contact', via: [:get, :post]

			get 'phones'
			get 'delete'
		end
	end

	get 'sitemap' => 'sitemap#index'
	get 'opensearch' => 'home#opensearch', as: :opensearch

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr" dir="ltr">
<head prefix="og: http://ogp.me/ns/website#">
	<meta charset="utf-8">

<%= render '/partials/graph' %>

	<%= stylesheet_link_tag 'application', media: 'all' %>
	<%= csrf_meta_tags %>

	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<link rel="shortcut icon" type="image/x-icon" href="<%= asset_url 'favicon.ico' %>" /> 
	<link rel="icon" type="image/x-icon" href="<%= asset_url 'favicon.ico' %>" />
	<link rel="apple-itouch-icon" href="<%= asset_url 'apple-touch-icon.png' %>" />

    <link rel="dns-prefetch" href="//static.mobile-d-occaz.fr">
    <link rel="dns-prefetch" href="//cdn.mobile-d-occaz.fr">

    <link rel="dns-prefetch" href="//maps.googleapis.com">
    <link rel="dns-prefetch" href="//maps.gstatic.com">
    <link rel="dns-prefetch" href="//csi.gstatic.com">
    <link rel="dns-prefetch" href="//mts0.googleapis.com">
    <link rel="dns-prefetch" href="//mts1.googleapis.com">
    <link rel="dns-prefetch" href="//fonts.googleapis.com">

    <link rel="dns-prefetch" href="//www.google-analytics.com">

    <link rel="dns-prefetch" href="//www.geoplugin.net">

    <link rel="search" type="application/opensearchdescription+xml" href="<%= opensearch_url(format: :xml) %>" title="Mobile d'occaz" />

	<%= render '/partials/meta' %>
</head>
<body>

	<% flash.each do |name, msg| %>
		<div class="flash <%= name%>">
			<%= msg %>
			<a class="close" href="#">Fermer</a>
		</div>
	<% end %>

	<%= render '/partials/header' %>

	<%= yield %>

	<%= render '/partials/footer' %>

	<%= javascript_include_tag 'application' %>
	<%= javascript_include_tag 'async', async: :true %>
	<%= yield :javascript %>

</body>
</html>